version: '2.4'

services:
  indexer:
    container_name: indexer
    build: .
    image: lto-indexer
    volumes:
      - indexer:/usr/app/lto-index
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - NODE_URL=https://testnet.lto.network
      - TRANSACTION_INDEXING=true
    networks:
      - lto

volumes:
  indexer:

networks:
  lto:
    driver: bridge
